"""empty message

Revision ID: 24a341000615
Revises: 
Create Date: 2025-04-24 16:51:33.428630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24a341000615'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_fk', sa.Integer(), nullable=False),
    sa.Column('fav_user_id_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fav_user_id_fk'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_fk', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('parish', sa.String(length=100), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('race', sa.String(length=50), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('fav_cuisine', sa.String(length=100), nullable=True),
    sa.Column('fav_colour', sa.String(length=50), nullable=True),
    sa.Column('fav_school_subject', sa.String(length=100), nullable=True),
    sa.Column('political', sa.Boolean(), nullable=True),
    sa.Column('religious', sa.Boolean(), nullable=True),
    sa.Column('family_oriented', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Favourite')
    op.drop_table('Profile')
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"User_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='User_pkey'),
    sa.UniqueConstraint('email', name='User_email_key'),
    sa.UniqueConstraint('username', name='User_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Profile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id_fk', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('parish', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('biography', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('race', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('birth_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fav_cuisine', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('fav_colour', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fav_school_sibject', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('political', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('religious', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('family_oriented', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id_fk'], ['User.id'], name='Profile_user_id_fk_fkey'),
    sa.PrimaryKeyConstraint('id', name='Profile_pkey')
    )
    op.create_table('Favourite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id_fk', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fav_user_id_fk', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fav_user_id_fk'], ['User.id'], name='Favourite_fav_user_id_fk_fkey'),
    sa.ForeignKeyConstraint(['user_id_fk'], ['User.id'], name='Favourite_user_id_fk_fkey'),
    sa.PrimaryKeyConstraint('id', name='Favourite_pkey')
    )
    op.drop_table('profiles')
    op.drop_table('favourites')
    op.drop_table('users')
    # ### end Alembic commands ###
